# we are going to create new workflow

# name: Book Practice workflow
# #on: [push, pull_request,workflow_dispatch] # cntl+ space to get autocomplete in side 
# # the bracket those we can it as triggers ON is a event
# on:
#   push:
#     branches: 
#       - main
#   workflow_dispatch:

# # on:
# #   push:
# #     branches: 
# #       - 'release/**'
# #     paths:
# #       - 'docs/**'
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo 'Hellow World from ${{ github.actor}}.'

# name of the workflow
name: book worklfow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

# jobs:
#   firstjob:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo " hellow world from ${{ github.actor}} "

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        if: github.ref == 'refs/heads/main'

      
    

