# we are going to create new workflow

name: Book Practice workflow
#on: [push, pull_request,workflow_dispatch] # cntl+ space to get autocomplete in side 
# the bracket those we can it as triggers ON is a event
on:
  push:
    branches: 
      - main
  workflow_dispatch:

# on:
#   push:
#     branches: 
#       - 'release/**'
#     paths:
#       - 'docs/**'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hellow World from ${{ github.actor}}.'
  


