name: Cloud SQL Table Creation

on:
  push:
    branches:
      - main

jobs:
  create_table:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: smiling-audio-398006
        service_account_key: ${{ secrets.SA_KEY }}
        export_default_credentials: true

    - name: Execute SQL command to create table
      uses: google-github-actions/cloud-sdk@master
      with:
        args: sql connect smiling-audio-398006:us-west3:rcm --user=sqlserver --quiet --project=smiling-audio-398006 --database=to_publish
