name: Deploy SQL Script to Cloud SQL

on:
  push:
    branches:
      - main  # Set to your main branch or appropriate branch

jobs:
  deploy:
    name: Deploy SQL Script
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.RCM_DB_SERVICE_ACCOUNT }}
        export_default_credentials: true
      
    - name: Retrieve password from Google Secrets Manager
      run: |
        gcloud secrets versions access latest --secret="rcm_db_password" > db_password.txt
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_PROJECT_ID }}
    
    - name: Execute SQL script on Cloud SQL instance
      run: |
        gcloud sql connect smiling-audio-398006:us-central1:rcmdatabase --user=sqlserver --password=$(cat db_password.txt) < arun/arun.sql
