name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: Ubuntu 23.04
    steps:
      - name: print status of work
        run:  echo "hellow world" 
    
      - name: print status of work
        run:  echo "hellow world" #
       
       
       
      
       
