name: NEW Run DB/DB_New_User_Creation/01_New_User_Creation_Script
on:

workflow_dispatch:

inputs:

version:

description: 'Provide the VERSION you want to deploy'

type: string

required: true

default: "1.0.6"

environment:

  description: "Environment to apply the changes"
  type: choice

  required: true

  options:

   "uat"

  default: "uat"

deploy:

 description: 'Deploy the scripts

type: boolean

required: true

default: true

SQL Instance:

description: "Select cloudsql instance name"

type: choice

required: true

options: actimize-uat-ber-mssql-app

default: actimize-uat-ber-mssql-app

gcpproject:

type: choice

description: 'Select GCP Project'

required: true
options: db-uat-yr1s-actimize-eri-001-1
default: db-uat-yris-actimize-eri-001-1

liquibase secret:

type: choice

description: 'Select Secret value for SQL Instance

required: true

options:

-UAT

default: UAT

env:

#SQL #SQL INSTANCE: "db-prd-htlf-actimize-eri-001-1:europe-west3:actimize-main-prd-sam-c-mssql-eri-001-1-tcp:1433" # INSTANCE: "db-prd-htlf-actimize-eri-001-1:europe-west3:actimize-main-prd-san-c-mssql-er1-001-1-tcp:1433" ##

# SAM-C RCM PROD DATABASE INSTANCE

SAM-C PROD SAM DATABASE INSTANCE

#SQL INSTANCE: "db-dev-84el-actimize-eri-001-1:europe-west3:actimize-dev-sam-apac-tuning-mssql-eri-001-1-tcp:1433

" ## DEV APAC SQL INSTANCE

#SQL INSTANCE: "db-prd-htlf-actimize-eri-001-1:europe-west3:actimize-prd-sam-c-mssql-eri-001-1-ekm-tcp:1433" ##

REGULAR EKM PROD DATABASE MAIN CONUAT

#SQL INSTANCE: "db-prd-htlf-actimize-eri-001-1:europe-west3:actimize-prd-san-c-mssql-eri-001-1-ekm2-tcp:1433" #

# EKM2 PROD DATABASE TUNNING ENV

SQL INSTANCE: "${{ github.event.inputs.gcpproject}): europe-west3:$({ github.event.inputs.SQL Instance))=tcp:1433"

ARTIFACTORY HOSTNAME: "artifactory.sdlc.ctl.gcp.db.com"

LIQUIBASE HOME: artifactory/mvn-public-local/com/db/actimize/db-actimize-liquibase-sqlserver

VERSION: ${{ github.event.inputs.version}}

-FOLDER NAME: db-actimize-liquibase-sqlserver-${{github.event.inputs.version}) -no_proxy: "metadata.google.internal, localhost,db.com"

jobs:

Trigger:

name: Trigger MF

uses: y253-q6ix/app-actimize-workflow-ext/.github/workflows/db_user_creation.yaml@db_user_migration

with:

version: ${{github.event.inputs.version})

environment: ${{ github.event.inputs.environment))

deploy: ${{ github.event.inputs.deploy }}

SQL Instance: ${{github.event.inputs.SQL Instance ))

gcpproject: ${{ github.event.inputs.gcpproject }}

liquibase_secret: ${{ github.event.inputs.liquibase_secret)}

secrets: inherit
