on:
  push:
    branches: [ master ]

jobs:
  db-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-google-cloud-sql-proxy@v1
        with:
          key: ${{secrets.RCM_DB_SERVICE_ACCOUNT}}
          connection: my-project:northamerica-northeast1:database
          port: 5432
