---
name: Deploy to Google Cloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{secrets.RCM_DB_SERVICE_ACCOUNT}}
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
      - name: Set environment variables (Optional)
        run: |
          echo "Setting environment variables"
          echo "DB_USER=sqlserver" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{secrets.RCM_DB_PASSWORD1}}" >> $GITHUB_ENV
      - name: Enter Instance Details (Optional - for demonstration)
      - name: Access Instance (Replace placeholders)
        run: |
          gcloud sql connect "${{secrets.INSTANCE_CONNECTION_NAME}}" \
                             --user="${{secrets.DB_USER}}" \
                             --password="${{secrets.RCM_DB_PASSWORD1}}" \
                             --quiet
      - name: Perform SQL operations (Optional)
