# name: Run SQL Script on PostgreSQL

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:
#     inputs:
#       INSTANCE_IP:
#         description: 'Value for rcm parameter'
#         required: true

# jobs:
#   execute_sql:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Install psql (if needed)
#         run: sudo apt-get update && sudo apt-get install -y postgresql-client

#       - name: Get input IP address (if applicable)
#         id: get-ip
#         run: echo "INSTANCE_IP=$(echo ${{ secrets.INSTANCE_IP }})" >> $GITHUB_ENV

#       - name: Run SQL script
#         run: psql -h ${{ secrets.SERVER_NAME }} -U ${{ secrets.DATABASE_USERNAME }} -d ${{ secrets.DATABASE_NAME }} -f your_script.sql

#         # Or, if using the input IP:
#         # run: psql -h ${{ secrets.SERVER_NAME }} -U ${{ secrets.DATABASE_USERNAME }} -d ${{ secrets.DATABASE_NAME }} -f your_script.sql -v:INSTANCE_IP=${{ env.INSTANCE_IP }}
